[package]
name = "calc"
version = "0.1.0"
authors = ["vafadehghan <vafa@dehghan.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "embed"
crate-type = ["dylib"]